---
title: "Nonlinear Dynamics in Exchange Rate Pass-Through and Inflation Persistence: The Case of Turkish Economy"
subtitle: Asian Journal of Economic Modeling
date: 2018-01-01
author:
  - name: Muhsin Ciftci
    url: https://mciftci.netlify.app
    affiliation: Central Bank of Türkiye
  - name: Muhammed Hasan Yilmaz
    affiliation: Central Bank of Türkiye
categories: 
   - Exchange Rate Pass-through
   - Inflation
doi: 10.18488/journal.8.2018.61.8.20
page-layout: article
---

## Important links

- [AI Generated Podcast:]{.ftcol1}

<iframe title="Nonlinear Dynamics in Exchange Rate Pass-Through and Inflation Persistence: The Case of Turkish Economy" allowtransparency="true" height="300" width="100%" style="border: none; min-width: min(100%, 430px);height:300px;" scrolling="no" data-name="pb-iframe-player" src="https://www.podbean.com/player-v2/?i=a6r56-17d60d6-pb&from=pb6admin&square=1&share=1&download=1&rtl=0&fonts=Arial&skin=1&font-color=auto&logo_link=episode_page&btn-skin=7&size=300" loading="lazy" allowfullscreen=""></iframe>

- [Link to the Paper](https://archive.aessweb.com/index.php/5009/article/view/297/539)

## Abstract
As a small open economy, inflation is still largely driven by exchange rate developments in Turkey. Despite the fact that exchange rate pass-through (ERPT) to inflation has declined after the adoption of explicit inflation targeting in 2003, its contribution to the consumer prices and producer prices inflation is still prominent. Furthermore, recent studies show that inflation persistence appears to be another issue preventing from achieving price stability. This paper aims to explore the non-linear dynamics of ERPT and inflation persistence in the case of Turkey by employing Smooth Transition Regression (STR) models. The main motivation of this study is to identify different regimes characterized by the magnitude of exchange rate movements in which ERPT and persistence in inflation indicators differ. Estimation results for the period 2003-2017 shows that inflation persistence and ERPT for Consumer Price Index (CPI) is high in regime with a sizeable import price shock. Additionally, STR estimation results indicate that ERPT and import price pass-through to Producer Price Index (PPI) is more influential in “high depreciation” regime.


