project:
  type: website

from: markdown+emoji
website:
  #title: 'Home'
  open-graph: true
  favicon: /media/profile.png
  image: /media/profile.png
  twitter-card:
    creator: "@ciftciphd"
    card-style: summary_large_image
  page-navigation: false
  page-footer:
    right: ":school:"
    border: false
  navbar:
    #search: false
    right:
      - href: index.qmd
        text: Home
      - text: Research
        href: research/research.qmd
      - text: Blog
        href: blog.qmd
bibliography: [bib/my_articles.bib, bib/my_wp.bib]
csl: styles/chicago.csl
format:
  html:
    linestretch: 2pt
    fontsize: 14pt
    theme: [styles/main.scss]
    lang: en
    date-format: long

execute: 
  freeze: auto
