project:
  type: website

freeze: true
from: markdown+emoji
website:
  #title: 'MC'
  open-graph: true
  favicon: /media/profile.png
  image: /media/profile.png
  twitter-card:
    creator: "@ciftciphd"
    card-style: summary_large_image
  page-navigation: true
  page-footer:
    right: "Made with :heart: and Quarto"
    border: false
  navbar:
    foreground: "#0D7680"
    search: false
    right:
      - href: index.qmd
        text: Home
      - text: Blog
        href: blog.qmd
      - text: Research
        href: research.qmd
format:
  html:
    theme: [simplex, css/colors.scss, css/metropolis.scss]
    css: css/style.css
    lang: en
    date-format: long
    highlight-style: tango